# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  # - name: Bio
  #   url: /
  #   weight: 10
  # - name: Papers
  #   url: /#papers
  #   weight: 11
  #   weight: 12
  # - name: News
  #   url: /#news
  #   weight: 13
  - name: Research Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Academic Service
    url: outreach/
    weight: 35
  - name: Talks
    url: events/
    weight: 37
  - name: Publications
    url: publications/
    weight: 40
  - name: Collaborators
    url: collaborators/
    weight: 45
  - name: Media
    url: media/
    weight: 50
